name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and run tests
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      # Build
      - name: Install dependencies
        run: dotnet restore src/MercadoPago/MercadoPago.csproj

      - name: Build
        run: dotnet build src/MercadoPago/MercadoPago.csproj --configuration Release --no-restore

      # Run Tests
      - name: Install tests dependencies
        run: dotnet restore src/MercadoPago.Tests/MercadoPago.Tests.csproj

      - name: Run tests
        run: dotnet test src/MercadoPago.Tests/MercadoPago.Tests.csproj --configuration Release --no-restore
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EMAIL: ${{ secrets.USER_EMAIL }}
